### ISSUE TITLE
Allow factorial specification of tests based on sets of options

### ISSUE THREAD

**Issue by whart222** [PyUtilib/pyutilib#10]
The pyutilib.testdriver should allow specifying multiple sets of options for a solver. It would then run a "full-factorial" suite of tests. For example:

```testsuites:
  solvers:
    solver_a:
      np:
        - 1
        - 2
        - 4
      strategy:
        - dive
        - pseudocost
    solver_b:
      np: 1
  problems:
    problem_1:
    problem_2:
```

would specify 14 tests.

This is on the wishlist because this capability has lots of difficult implications, including how it gets implemented, how fractional specifications are managed (in the 'tests' block), and how tests get named. If this was spelled out in more detail, I'd be willing to look into this. However, this might be a nice extension for John or Dave to dig into to help familiarize themselves with this code.

It is an open question how to consistently name the individual tests.

**Comment by whart222** [comment]
The pyutilib.testdriver YAML input specification could support a section that allows us to specify a subset of the full factorial set of tests. For example:
```
testsuites:
   suite_a:
      solvers:
         solver_a:
         solver_b:
      problems:
         problem_1:
         problem_2:
      tests:
         - solver_a_problem_1
         - solver_b_problem_2

would only run solver_a on problem_1 and solver_b on problem_2. Additionally,

testsuites:
   suite_a:
      solvers:
         solver_a:
         solver_b:
         solver_c:
      problems:
         problem_1:
         problem_2:
      tests: */4
```
would run 1/4 of the full-factorial design (distributed in some statistically meaningful manner).
